### ISSUE TITLE
Trying to edit?

### ISSUE THREAD

**Issue by Castawayz** [thomas-crane/famebot#34]
I noticed that the famebot was moving back and forth in the train or was avoiding gods, so I changed the code in the plugin.cs folder, but how do I get everything else into the .dll file that is runnable by Krelay? Thanks.

**Comment by thomas-crane** [comment]
This raises a good point which is that I haven't included a dedicated section on how to build your own version of the plugin anywhere in the readme. This section here (How to get this plugin Option 2):

>1. Clone this repo to a folder somewhere on your computer.
>
>2. Open FameBot.sln using Visual Studio 2015.
>
>3. Right click on the FameBot project and select build.
>
>4. Right click on the Solution and select Open Folder in File Explorer.
>
>5. Open the 'Release' folder.
>
>6. Copy FameBot.dll to the Plugins folder of your KRelay.
>
>7. Start using the FameBot.

briefly describes how you can build the source.

FYI, if you are only trying to turn off the enemy avoidance feature, the latest version on GitHub actually lets you do this. There is a new check box in the config manager window which lets you enable or disable the feature.

**Comment by Castawayz** [comment]
Thanks! I'm currently trying to edit it so that the bot doesn't really seem like a bot and will seem like a regular player. Is there any way you could do that?

**Comment by thomas-crane** [comment]
Closing this for now since the issue has been resolved.

I would suggest adding a certain level of 'noise' to the target position for the bot. (e.g. randomly add plus or minus 3 game tiles to the target position X and Y). This will reduce the likelihood that your bot will be moving in exactly the same manner as other bots and is a good place to start for emulating natural behaviour. Something else to consider would be how often to add the noise. If it is too often the bot will appear more robotic, but if it is too infrequent the benefit will be reduced.
