### ISSUE TITLE
Client disconnected

### ISSUE THREAD

**Issue by qainaas** [thomas-crane/famebot#36]
"Client disconnected. Waiting a few seconds before trying to press play..."
This keeps happening when I go afk. When I come back I find my PPE running against the bottom left corner of nexus. Any help to make the client not disconnect?

**Comment by thomas-crane** [comment]
The client is running towards the bottom left corner of the nexus because in the X18.0.0 update the nexus map was changed so the bot needs new positions.
You can update the bot positions by following these steps:
1. Stand in a spot where you are healed by the fountains
2. Use the command: "/famebot set fountainposition"
3. Stand in a spot where you can see the realms
4. Use the command "/famebot set realmposition"

This will stop the bot walking to the wrong place.

**Comment by qainaas** [comment]
Does the bot automatically join the realm or do I have to do that manually?

**Comment by thomas-crane** [comment]
The bot will walk to the most full realm and try to connect to it.
If you haven't already, you can [watch this video](https://www.youtube.com/watch?v=xYY3iSDlibw) which shows how to install the bot and gives a short demo of the expected behaviour.

**Comment by qainaas** [comment]
Thanks!
